services:
  cads_bridge:
    build:
      args:
        TARGETARCH: x64
    labels:
      com.microsoft.visual-studio.project-name: "CadsBridge"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5550
      - AWS__ServiceURL=http://cads-bridge-localstack-emulator:4566
      - Storage__Internal__BucketName=cads-bridge-internal-bucket
      - Storage__Internal__HealthcheckEnabled=true
      - Storage__External__BucketName=cads-bridge-external-bucket
      - Storage__External__HealthcheckEnabled=true
    ports:
      - "5550"
    volumes:
      # Mac-specific paths for user secrets and HTTPS certificates
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro