name: 'cads-bridge'
services:
  
  cads_bridge:
    container_name: "cads-bridge"
    platform: linux
    image: cads_bridge
    build: ./
    ports:
      - '5550:5550'
    depends_on: []
    env_file:
      - './compose/aws.env'
    environment:
      PORT: 5550
      LOCALSTACK_ENDPOINT: http://cads-localstack:4566
    networks:
      - cads-network

networks:
  cads-network:
    external: true